import 'dart:async';
import 'dart:convert';
import 'dart:developer' show log;
import 'dart:io' show Directory, File, Platform;
import 'dart:typed_data';

import 'package:adhan/adhan.dart';
import 'package:arabic_justified_text/arabic_justified_text.dart';
import 'package:archive/archive.dart' show ZipDecoder;
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show MethodChannel, rootBundle;
import 'package:flutter_rounded_progress_bar/flutter_rounded_progress_bar.dart';
import 'package:flutter_rounded_progress_bar/rounded_progress_bar_style.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:gap/gap.dart';
import 'package:gauge_indicator/gauge_indicator.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:hijri_date/hijri_date.dart';
import 'package:home_widget/home_widget.dart';
import 'package:horizontal_week_calendar/horizontal_week_calendar.dart';
import 'package:intl/intl.dart' as intl;
import 'package:just_audio/just_audio.dart';
import 'package:latlong2/latlong.dart';
import 'package:nominatim_geocoding/nominatim_geocoding.dart' as nominatim;
import 'package:path/path.dart' as path;
import 'package:path_provider/path_provider.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share_plus/share_plus.dart';
import 'package:slide_countdown/slide_countdown.dart';
import 'package:solar_icons/solar_icons.dart';
import 'package:square_percent_indicater/square_percent_indicater.dart';

import '/core/utils/constants/extensions/bottom_sheet_extension.dart';
import '/core/utils/constants/extensions/convert_number_extension.dart';
import '/core/utils/constants/extensions/extensions.dart';
import '/core/utils/constants/extensions/svg_extensions.dart';
import '/core/utils/constants/string_constants.dart';
import '/core/widgets/home_widget/home_widget.dart';
import '../../../core/services/location/locations.dart';
import '../../../core/services/notifications_helper.dart';
import '../../../core/utils/constants/lists.dart';
import '../../../core/utils/constants/shared_preferences_constants.dart';
import '../../../core/utils/constants/svg_constants.dart';
import '../../../core/utils/helpers/date_formatter.dart';
import '../../../core/widgets/reactive_number_text.dart';
import '../../core/services/internet_connection_controller.dart';
import '../../core/widgets/active_location_button.dart';
import '../../core/widgets/animated_drawing_widget.dart';
import '../../core/widgets/app_bar_widget.dart';
import '../../core/widgets/container_button_widget.dart';
import '../../core/widgets/custom_switch_widget.dart';
import '../calendar/events.dart';
import '../controllers/general/general_controller.dart';
import 'data/model/adhan_data.dart';
import 'data/model/prayer_details.dart';
import 'hijri_prayer_widget/prayer_now_widget.dart';

part 'controller/adhan/adhan_controller.dart';
part 'controller/adhan/adhan_state.dart';
part 'controller/adhan/extensions/adhan_getters.dart';
part 'controller/adhan/extensions/adhan_ui.dart';
part 'controller/adhan/extensions/location_extension.dart';
part 'controller/adhan/extensions/monthly_prayer_cache.dart';
part 'controller/adhan/extensions/prayer_cache_manager.dart';
part 'controller/prayer_progress_controller.dart';
part 'controller/prayers_notifications/extensions/prayer_times_serialization.dart';
part 'controller/prayers_notifications/extensions/prayers_noti_ui.dart';
part 'controller/prayers_notifications/extensions/schedule_daily_extension.dart';
part 'controller/prayers_notifications/noti_state.dart';
part 'controller/prayers_notifications/prayers_notifications_controller.dart';
part 'data/model/prayer_list.dart';
part 'helpers/adhan_audio_downloader.dart';
part 'hijri_prayer_widget/active_location_or_prayer_widget.dart';
part 'screen/prayer_screen.dart';
part 'widgets/activate_adhan_button.dart';
part 'widgets/hijri_date_widget.dart';
part 'widgets/loading_widget.dart';
part 'widgets/prayer_build.dart';
part 'widgets/prayer_details.dart';
part 'widgets/prohibition_details.dart';
part 'widgets/settings/adhan_sounds.dart';
part 'widgets/settings/pick_calculation_method.dart';
part 'widgets/settings/play_button.dart';
part 'widgets/settings/prayer_settings.dart';
part 'widgets/settings/set_timing_calculations.dart';
part 'widgets/settings/setting_prayer_times.dart';
part 'widgets/share/share_card.dart';
part 'widgets/share/share_controller.dart';
part 'widgets/share/share_options_widget.dart';
part 'widgets/slide_countdown_widget.dart';
