// ignore_for_file: constant_identifier_names

const String LANG = 'lang';
const String LANG_NAME = 'langName';
const String LANGUAGE_FONT = 'languageFont';
const String SET_THEME = 'SET_THEME';
const String LAST_SHOWN_UPDATE_INDEX = 'LAST_SHOWN_UPDATE_INDEX';
const String ACTIVE_LOCATION = 'ACTIVE_LOCATION';
const String IS_LOCATION_ACTIVE = 'IS_LOCATION_ACTIVE';
const String SHAFI = 'SHAFI';
const String HANAFI = 'HANAFI';
const String HIGH_LATITUDE_RULE = 'HIGH_LATITUDE_RULE';
const String AUTO_CALCULATION = 'AUTO_CALCULATION';
const String ADHAN_NUMBER = 'ADHAN_NUMBER';
const String ADHAN_SELECT = 'ADHAN_SELECT';
const String ADJUSTMENT_FAJR = 'ADJUSTMENT_FAJR';
const String ADJUSTMENT_DHUHR = 'ADJUSTMENT_DHUHR';
const String ADJUSTMENT_ASR = 'ADJUSTMENT_ASR';
const String ADJUSTMENT_MAGHRIB = 'ADJUSTMENT_MAGHRIB';
const String ADJUSTMENT_ISHA = 'ADJUSTMENT_ISHA';
const String ADJUSTMENT_THIRD = 'ADJUSTMENT_THIRD';
const String ADJUSTMENT_MIDNIGHT = 'ADJUSTMENT_MIDNIGHT';
const String ADJUSTMENT_SUNRISE = 'ADJUSTMENT_SUNRISE';
const String ADHAN_PATH = 'ADHAN_PATH';
const String ADHAN_PATH_FAJIR = 'ADHAN_PATH_FAJIR';
const String QIBLA_WIDGET_INDEX = 'QIBLA_WIDGET_INDEX';
const String CURRENT_LOCATION = 'CURRENT_LOCATION';
const String PRAYER_TIME_DATE = 'PRAYER_TIME_DATE';
const String PRAYER_TIME = 'PRAYER_TIME';
const String ADHAN_PATH_AUDIO = 'ADHAN_PATH_AUDIO';
const String ADHAN_PATH_FAJIR_AUDIO = 'ADHAN_PATH_FAJIR_AUDIO';
const String ADHAN_PATH_INDEX = 'ADHAN_PATH_INDEX';

/// مقطع iOS القصير (≤30 ثانية) من الحزمة المحمّلة؛ يُحل كصوت إشعار.
const String ADHAN_PATH_SEGMENT_AUDIO = 'ADHAN_PATH_SEGMENT_AUDIO';

/// فهرس المقرئ المختار حالياً في كتالوج أصوات الأذان.
const String ADHAN_SELECTED_INDEX = 'ADHAN_SELECTED_INDEX';
// Iqama times
const String IQAMA_OFFSET_FAJR = 'IQAMA_OFFSET_FAJR';
const String IQAMA_OFFSET_DHUHR = 'IQAMA_OFFSET_DHUHR';
const String IQAMA_OFFSET_ASR = 'IQAMA_OFFSET_ASR';
const String IQAMA_OFFSET_MAGHRIB = 'IQAMA_OFFSET_MAGHRIB';
const String IQAMA_OFFSET_ISHA = 'IQAMA_OFFSET_ISHA';
const String IQAMA_NOTIFICATIONS_ENABLED = 'IQAMA_NOTIFICATIONS_ENABLED';
const String SHOW_IQAMA_TIMES = 'SHOW_IQAMA_TIMES';

const String FIRST_LAUNCH = 'FIRST_LAUNCH';

// Cities feature
const String SAVED_CITIES = 'SAVED_CITIES';
